### ISSUE TITLE
List of bugs to fix

### ISSUE THREAD

**Issue by Shawn-Cameron** [brvv/qix-like#9]
- List index out of range when adding sparx/spiders after death (happens sometimes)
- Walkable nodes on border sometimes convert to claimed node 
- Going to drawing mode and not going on an empty node sometimes produces an error

**Comment by brvv** [comment]
I can't replicate the last bug

Also found a bug: 
`line 118, in _add_to_claim
    self.claimed += self.node_percentage * len(set( [(c[0],c[1]) for c in lst] ))
TypeError: 'NoneType' object is not iterable`

set c is None for some reason

**Comment by brvv** [comment]
This guy popped up when I died:

```
line 518, in _add_sparx
    self.sparxs.append(Sparx((self.NODE_SIZE,self.NODE_SIZE), valid_coordinates,adjacent[0]))
IndexError: list index out of range
```

**Comment by brvv** [comment]
Probably resolved the list index out of range bug

**Comment by brvv** [comment]
Fixed walkable nodes turning to claimed nodes

**Comment by brvv** [comment]
I'm not sure what bug number 3 means, and I don't think i can replicate it - after fixing the previous two bugs i can't get the game to crash
